# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)

User.create(email: "st118437@ait.asia", is_super_admin: true, is_member: false, is_master_admin: false)
User.create(email: "mdailey@ait.asia", is_super_admin: true, is_member: false, is_master_admin: false)
Committee.create(name: 'Culture and Gender', description: 'Gender and Culture committee aims to bind all AITians of diverse culture and ethnicity by fostering creative and entertaining ideas. Like previous years, we will be organizing exciting events. We encourage your participation and promise to make your stay in AIT a memorable one.')
Committee.create(name: 'Campus and Environment', description: 'Campus and Environment committee works throughout the semester for the students and campus betterment in order to create a trouble-free life at AIT. We look forward to ensure to protect and nourish the natural beauty of the campus by providing all the basic facilities to the students. We hope to organize various activities and awareness programs which helps in inducing the responsibility of individuals and promoting CLEAN GREEN AIT.')
Committee.create(name: 'External Affairs', description: 'SU external affairs mainly works to link AIT with other universities in Thailand and abroad. The main motive of the committee is to ensure that AIT students get information about happenings in and around Thailand. We provide platform to participate in those events. We are also organizing events like career fair which would assist graduates for professional career life.')
Committee.create(name: 'Film & Entertainment', description: 'SU external affairs mainly works to link AIT with other universities in Thailand and abroad. The main motive of the committee is to ensure that AIT students get information about happenings in and around Thailand. We provide platform to participate in those events. We are also organizing events like career fair which would assist graduates for professional career life.')
Committee.create(name: 'Academic Affairs', description: 'Student union academics committee is dedicated to enhance students’ technical and managerial skills. We will organize useful seminars ranging from Thai language course to motivational workshops. We plan to encourage the students by arranging Academic Olympiad and Research Exhibition. We also plan to launch a magazine for the first time which will publish literature prepared by the AITians and will introduce beautiful features of their countries.')
Committee.create(name: 'Accomodation and Reservation', description: 'The accommodation and reservations committee is responsible for picking up the new students from the airport, providing them with temporary accommodation till the day of the lottery and then conduct lottery for proving permanent accommodation to the new students. We are also responsible for organizing Welcome Dinner to inform the students about AIT Campus, Student Union and the activities planned for the new semester.')
Committee.create(name: 'Assets and Recreation', description: 'SU assets and recreation committee is organized to promote unity and co-operation amongst AIT community in the environment of socializing and relaxing. We serve as a social hub in order to offer the temporary comfort zone for students who is going to be surrounded by ton of academic loads, and we host screening the biggest sporting events (football, rugby, cricket etc.).')
Committee.create(name: 'Sports', description: 'SU sports committee is responsible for organizing most of the sporting activities in AIT including welcome games, mini marathon and mini Olympics. These sports activities help the students to improve their accountability, dedication, and leadership, among many other traits. The main goal of these events are to further improve the friendship between communities and to strengthen the bonds inside the one big AIT family.')
Committee.create(name: 'Leisure', description: 'Because student life is not all about study, SU leisure aims to bring you new experiences. Our missions are to organize welcome trip and grand trip. We will try our best to make you life at AIT more excited. Finally, we hope that you get a good experience from our trips. See you guys on the trip.')
Committee.create(name: 'Media Affairs', description: 'SU Media Affairs committee works towards providing an effective means of communication between the student union and the AIT student community. We cover all events organized by SU and publish into monthly newsletter, website, official Facebook page, SU App and YouTube channel. Through media, we hope to help you to capture the wonderful memories you create here at AIT.')
